### ISSUE TITLE
gnucashxml is not available anymore from the GitHub address

### ISSUE THREAD

**Issue by pmiddend** [mbugert/cashdash#1]
Apparently the repo was deleted by the author?

**Comment by mbugert** [comment]
Yes, ugh. I replaced it with the most recent fork of that project I could find (see readme) which made it work again for me.

I'm about 75% sure things are working correctly now; for some reason, the assets plot was hovering around -300€ for my wallet account throughout most of 2020, but that could have been me going overboard with equalizing transactions last year... :sweat_smile:

The dependency on this project is one of the main reasons why this project is still pre-alpha. I will get back to it when the time is right, but that could take a few months.
